In [2]:
import numpy as np

creating array

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1,2,3,4,5,6])

In [ ]:
a[2]

np.int64(10)

In [9]:
a[2] = 10

In [11]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [13]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
n[0, 1]

np.int64(2)

In [15]:
n[:, 1]

array([2, 5, 8])

In [16]:
np.random.seed(2)

In [17]:
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [18]:
np.random.randn(5, 2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [19]:
np.random.randint(0, 100, size=(5, 2))

array([[83, 31],
       [66, 80],
       [52, 76],
       [50,  4],
       [90, 63]], dtype=int32)

In [21]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [22]:
a+1

array([1, 2, 3, 4, 5])

In [23]:
a ** 2

array([ 0,  1,  4,  9, 16])

a.min()
a.max()
a.sum()
a.mean()
a.std()

In [24]:
a >= 2

array([False, False,  True,  True,  True])

In [25]:
a[a >= 2]

array([2, 3, 4])

In [27]:
x = np.array([5,10,15,20,25])
x

array([ 5, 10, 15, 20, 25])

In [28]:
x[x>=12]

array([15, 20, 25])

In [30]:
x*3

array([15, 30, 45, 60, 75])

linear algebra

In [31]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [33]:
u+v

array([3, 4, 5, 8])

In [34]:
u*v

array([ 2,  0,  0, 12])

In [35]:
u.dot(v)

np.int64(14)

In [37]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [36]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [38]:
U.dot(v)

array([14,  5,  5])

In [39]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [42]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Pandas

In [44]:
import pandas as pd

DataFrame = whole table
Series    = one column

In [45]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 2000],
    ['Hyundai', 'Sonata', 2017, None, 27150],
    ['Lotus', 'Elise', 2010, 218, 54990],
    ['GMC', 'Acadia', 2017, 194, 34450],
    ['Nissan', 'Frontier', 2017, 261, 32340],
]

columns = ['Make', 'Model', 'Year', 'Engine HP', 'MSRP']

df = pd.DataFrame(data,columns=columns)
df

      Make     Model  Year  Engine HP   MSRP
0   Nissan    Stanza  1991      138.0   2000
1  Hyundai    Sonata  2017        NaN  27150
2    Lotus     Elise  2010      218.0  54990
3      GMC    Acadia  2017      194.0  34450
4   Nissan  Frontier  2017      261.0  32340

In [46]:
df.head()

      Make     Model  Year  Engine HP   MSRP
0   Nissan    Stanza  1991      138.0   2000
1  Hyundai    Sonata  2017        NaN  27150
2    Lotus     Elise  2010      218.0  54990
3      GMC    Acadia  2017      194.0  34450
4   Nissan  Frontier  2017      261.0  32340

In [47]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [49]:
print(df.loc[1])
print(df.iloc[1])

Make         Hyundai
Model         Sonata
Year            2017
Engine HP        NaN
MSRP           27150
Name: 1, dtype: object
Make         Hyundai
Model         Sonata
Year            2017
Engine HP        NaN
MSRP           27150
Name: 1, dtype: object

loc  → label 
iloc → integer position

In [50]:
df[
    (df['Make'] == 'Nissan') &
    (df['Year'] >= 2015)
]

     Make     Model  Year  Engine HP   MSRP
4  Nissan  Frontier  2017      261.0  32340

In [51]:
df['Make'].str.lower()

0     nissan
1    hyundai
2      lotus
3        gmc
4     nissan
Name: Make, dtype: str

In [52]:
df['Make'].str.replace(' ', '_')

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [53]:
df['MSRP'].mean()
df['MSRP'].min()
df['MSRP'].max()

np.int64(54990)

In [54]:
df['Make'].nunique()

4

In [55]:
df.isnull().sum()

Make         0
Model        0
Year         0
Engine HP    1
MSRP         0
dtype: int64

In [56]:
df.groupby('Make')['MSRP'].mean()

Make
GMC        34450.0
Hyundai    27150.0
Lotus      54990.0
Nissan     17170.0
Name: MSRP, dtype: float64

df.head()
df.shape
df.columns
df.dtypes

df['column']
df[['col1', 'col2']]

df.loc[]
df.iloc[]

df[condition]

df.describe()
df.nunique()
df.isnull().sum()

df.groupby(...)

df['column'].values